import Algebra.Prelude
import Algebra.Patches

open DihedralGroup

open Cardinal in
example {H : Type*} [Fintype H] : #H = Fintype.card H := mk_fintype H

-- This section gives a way to reduce the powers to the smallest possible. It's
-- what Dummit & Foote call the "least residue" powers.
section Prep
variable {G : Type*} [Group G] {x : G}

lemma IsOfFinOrder.exists_lt_order_eq_pow (hx : IsOfFinOrder x) (n : ℕ)
  : ∃ m < orderOf x, x ^ m = x ^ n
  := ⟨n % orderOf x, Nat.mod_lt n hx.orderOf_pos , pow_mod_orderOf x n⟩

lemma IsOfFinOrder.exists_lt_order_eq_zpow (hx : IsOfFinOrder x) (n : ℤ)
  : ∃ m < orderOf x, x ^ m = x ^ n
  := by --
  let m := n % orderOf x
  have hmeq : m = m.toNat := by
    rw [Int.eq_natCast_toNat]
    refine Int.emod_nonneg n ?_
    rw [Int.natCast_ne_zero_iff_pos]
    exact hx.orderOf_pos
  use m.toNat
  have : x ^ m = x ^ m.toNat := by
    rw [hmeq]
    exact zpow_natCast x m.toNat
  rw [<-this]
  refine ⟨?_, zpow_mod_orderOf x n⟩
  refine (Int.toNat_lt ?_).mpr ?_
  · exact Int.natCast_toNat_eq_self.mp hmeq.symm
  · refine Int.emod_lt_of_pos n ?_
    exact Int.natCast_pos.mpr hx.orderOf_pos -- ∎

end Prep

-- If H = ⟨x⟩, then |H| = |x|.
section Proposition2
variable {H : Type*} [Group H] {x : H}

-- Partial goal: that |⟨x⟩| = |x|.
example (hx : IsOfFinOrder x) : { x ^ n | n < orderOf x }.ncard = orderOf x
  := by --
  let N : Set ℕ := Finset.range (orderOf x)
  have heq : { x ^ n | n < orderOf x } = N.image (x ^ ·) := by
    dsimp only [N]
    rw [Finset.coe_range]
    rfl
  rw [heq]
  refine le_antisymm ?_ ?_
  · dsimp only [N]
    have : N.ncard = orderOf x := by
      rw [Set.ncard_coe_finset (Finset.range (orderOf x))]
      exact Finset.card_range (orderOf x)
    conv => rhs; rw [<-this]
    change ((x ^ ·) '' N).ncard ≤ N.ncard
    refine Set.ncard_image_le ?_
    exact Finset.finite_toSet (Finset.range (orderOf x))
  · refine Set.le_ncard_of_inj_on_range (x ^ ·) ?_ ?_ ?_
    · intro n hn
      refine ⟨n, ?_, rfl⟩
      dsimp only [N]
      rw [Finset.coe_range]
      exact hn
    · intro i hi j hj (heq : x ^ i = x ^ j)
      rw [IsOfFinOrder.pow_eq_pow_iff_modEq hx] at heq
      exact Nat.ModEq.eq_of_lt_of_lt heq hi hj
    · exact Set.toFinite ((x ^ ·) '' N) -- ∎

-- Different ways of writing ⟨x⟩ in Lean.
example : Subgroup.zpowers x = Subgroup.closure {x} := Subgroup.zpowers_eq_closure x

-- |⟨x⟩| = |x|. So if a group is generated by one element (or cyclic), then the
-- cardinality of that group is the order of that element.
--
-- Note that in Mathlib, the convention is that if a group element has infinite
-- order, then `orderOf` gives 0. Similarly if a type has infinite cardinality,
-- then `Nat.card` gives 0.
example (h : Subgroup.closure {x} = ⊤) : Nat.card H = orderOf x
  := by --
  rw [<-Subgroup.zpowers_eq_closure x] at h
  exact (orderOf_eq_card_of_zpowers_eq_top h).symm -- ∎

end Proposition2

-- If xⁿ = 1, then |x| divides n.
--
-- In fact, the theorems below show one better: that xⁿ = 1 ↔ |x| divides n.
section Proposition3
variable {G : Type*} [Group G]

example (x : G) (n : ℕ) : orderOf x ∣ n ↔ x ^ n = 1 := orderOf_dvd_iff_pow_eq_one
example (x : G) (n : ℕ) : orderOf x ∣ n ↔ x ^ n = 1
  := by --
  refine ⟨?_, ?_⟩
  · intro ⟨k, hk⟩
    subst hk
    rw [pow_mul, pow_orderOf_eq_one]
    exact one_pow k
  · intro h
    -- Handle the easy case where n = 0 first.
    rcases Nat.eq_zero_or_pos n with h₀ | hn
    · subst h₀
      exact Nat.dvd_zero _
    -- Now for when n > 0.
    have hF : IsOfFinOrder x := by
      rw [isOfFinOrder_iff_pow_eq_one]
      exact ⟨n, hn, h⟩
    let m := orderOf x
    have hm : x ^ m = 1 := pow_orderOf_eq_one x
    have hmn : m ≤ n := orderOf_le_of_pow_eq_one hn h
    let q := n / m
    let r := n % m
    have hqr : m * q + r = n := Nat.div_add_mod n m
    rw [<-hqr, pow_add, pow_mul, hm, one_pow, one_mul] at h
    have hrm : r < m := Nat.mod_lt n hF.orderOf_pos
    have hr₀ : r = 0 := by
      by_contra hr
      have hr : 0 < r := Nat.zero_lt_of_ne_zero hr
      exact hrm.not_ge (orderOf_le_of_pow_eq_one hr h)
    rw [hr₀, add_zero] at hqr
    use q
    exact hqr.symm -- ∎

example (x : G) (m n : ℕ) : x ^ m = 1 → x ^ n = 1 → x ^ gcd m n = 1
  := by --
  intro hm hn
  let d : ℤ := gcd m n
  have hm' : orderOf x ∣ m := orderOf_dvd_of_pow_eq_one hm
  have hn' : orderOf x ∣ n := orderOf_dvd_of_pow_eq_one hn
  rw [<-orderOf_dvd_iff_pow_eq_one]
  exact dvd_gcd hm' hn' -- ∎

example (x : G) (m n : ℤ) : x ^ m = 1 → x ^ n = 1 → x ^ gcd m n = 1
  := by --
  intro hm hn
  let m' := m.natAbs
  let n' := n.natAbs
  let d := gcd m' n'
  have hd : d = gcd m n := Int.neg_inj.mp rfl
  have hn' : x ^ n' = 1 := pow_natAbs_eq_one.mpr hn
  have hm' : x ^ m' = 1 := pow_natAbs_eq_one.mpr hm
  have hm' : orderOf x ∣ m' := orderOf_dvd_of_pow_eq_one hm'
  have hn' : orderOf x ∣ n' := orderOf_dvd_of_pow_eq_one hn'
  rw [<-hd, zpow_natCast x d, <-orderOf_dvd_iff_pow_eq_one]
  exact dvd_gcd hm' hn' -- ∎

-- The method that Dummit & Foote used.
example (x : G) (m n : ℤ) : x ^ m = 1 → x ^ n = 1 → x ^ gcd m n = 1
  := by --
  intro hm hn
  if hm₀ : m = 0 then
    subst hm₀
    rw [gcd_zero_left, <-Int.abs_eq_normalize, zpow_abs_eq_one x n]
    exact hn
  else if hn₀ : n = 0 then
    subst hn₀
    rw [gcd_zero_right, <-Int.abs_eq_normalize, zpow_abs_eq_one x m]
    exact hm
  else
    obtain ⟨a, b, h⟩ := Int.gcd_eq_sum hm₀ hn₀
    have : x ^ gcd m n = x ^ (m.gcd n : ℤ) := zpow_eq_zpow_iff_modEq.mpr rfl
    rw [this, <-h, zpow_add, zpow_mul, zpow_mul, hm, hn, one_zpow, one_zpow, one_mul] -- ∎

end Proposition3

-- Any two cyclic groups of the same order are isomorphic. More specifically,
--  (1) if ⟨x⟩ and ⟨y⟩ are both cyclic groups of order n. Then the map
--          φ : ⟨x⟩ → ⟨y⟩,  φ(xᵏ) = yᵏ
--      is well-defined and is an isomorphism.
--  (2) if ⟨x⟩ is an infinite cyclic group, the map
--          φ : ℤ → ⟨x⟩,  φ(k) = xᵏ
--      is well-defined and is an isomorphism.
section Theorem4
variable {G H : Type*} [Group G] [Group H] {x : G} {y : H}

-- For finite-order cyclic groups, this function provides an interface for
-- extracting a ℕ power instead of a ℤ.
example (hx : IsOfFinOrder x) (hG : Subgroup.zpowers x = ⊤)
  : ∀ g : G, ∃ k : ℕ, x ^ k = g
  := by --
  intro g
  let n : ℤ := orderOf x
  have hn₀ : 0 < n := Int.natCast_pos.mpr hx.orderOf_pos
  have hg := Subgroup.mem_top g
  rw [<-hG] at hg
  rw [Subgroup.mem_zpowers_iff] at hg
  obtain ⟨k, hk⟩ := hg
  let i := k % n
  have hi₀ : 0 ≤ i := Int.emod_nonneg k hn₀.ne'
  use i.natAbs
  have : x ^ i.natAbs = x ^ i := by
    rw [<-Int.natAbs_of_nonneg hi₀]
    exact (zpow_natCast x i.natAbs).symm
  rw [this]
  rw [zpow_mod_orderOf]
  exact hk -- ∎

-- In part (1) of Theorem 4, we deal with two cyclic groups of the same order.
section Part1
variable (heq : orderOf x = orderOf y)
  (hG : Subgroup.zpowers x = ⊤)
  (hH : Subgroup.zpowers y = ⊤)

noncomputable example (hFx : IsOfFinOrder x) : G ≃* H
  := by --
  have hFy : IsOfFinOrder y := by
    rw [<-orderOf_pos_iff, <-heq, orderOf_pos_iff]
    exact hFx
  -- Some extra results.
  have hG_card : orderOf x = Nat.card G := orderOf_eq_card_of_zpowers_eq_top hG
  have hH_card : orderOf y = Nat.card H := orderOf_eq_card_of_zpowers_eq_top hH
  have : Nat.card G = Nat.card H := by
    rw [<-hG_card, <-hH_card];
    exact heq
  -- The main solve.
  let φ₁ := zpowers_equiv_zmod_orderOf hG
  let φ₂ := zpowers_equiv_zmod_orderOf hH
  rw [<-heq] at φ₂
  have h (φ : Additive G ≃+ Additive H) : G ≃* H
    := by --
    refine { toEquiv := Additive.ofMul.trans (φ.toEquiv.trans Additive.ofMul.symm), map_mul' := ?_ }
    intro g₁ g₂
    rw [AddEquiv.toEquiv_eq_coe, Additive.ofMul_symm_eq, Equiv.toFun_as_coe]
    simp only [Equiv.trans_apply, ofMul_mul, EquivLike.coe_coe, map_add, toMul_add] -- ∎
  exact h (φ₁.trans φ₂.symm) -- ∎

end Part1

-- In part(2), the claim is that if ⟨x⟩ = ∞, then ⟨x⟩ ≃ ℤ.
section Part2
variable (hG : Subgroup.zpowers x = ⊤)
noncomputable example (hx : ¬IsOfFinOrder x) : G ≃ ℤ
  := by --
  have := zpowers_equiv_zmod_orderOf hG
  rw [orderOf_eq_zero hx] at this
  exact this.toEquiv -- ∎

end Part2

end Theorem4

section Proposition6
open Subgroup
variable {G : Type*} [Group G] {x : G} (hG : zpowers x = ⊤)

-- if |x| = ∞, then G = ⟨xᵃ⟩ if and only if a = ±1.
example (hx : ¬IsOfFinOrder x) {a : ℤ} : zpowers (x ^ a) = ⊤ ↔ a = 1 ∨ a = -1
  := by --
  constructor
  · intro htop
    have hx := Subgroup.mem_top x
    rw [<-htop, Subgroup.mem_zpowers_iff] at hx
    obtain ⟨k, hk⟩ := hx
    rw [<-zpow_mul x a k, <-mul_left_inj x⁻¹, mul_inv_cancel] at hk
    rw [<-zpow_neg_one, <-zpow_add, Int.add_neg_one] at hk
    rw [<-orderOf_dvd_iff_zpow_eq_one] at hk
    rw [orderOf_eq_zero hx, CharP.cast_eq_zero, zero_dvd_iff] at hk
    have : a * k = 1 := Int.eq_of_sub_eq_zero hk
    exact Int.eq_one_or_neg_one_of_mul_eq_one this
  · intro ha
    cases ha with
    | inl ha =>
      subst ha
      rw [zpow_one]
      exact hG
    | inr ha =>
      have : zpowers x ≤ zpowers (x ^ a) := by
        refine zpowers_le_of_mem ⟨-1, ?_⟩
        subst ha
        change (x ^ (-1)) ^ (-1) = x
        rw [<-zpow_mul, Int.neg_mul_neg, mul_one, zpow_one]
      exact eq_top_mono this hG -- ∎

end Proposition6
