import Algebra.Prelude

open DihedralGroup

universe u
variable {H : Type u}

open Cardinal in
example [Fintype H] : #H = Fintype.card H := mk_fintype H

section Proposition2
variable [Group H] {x : H}

-- Partial goal: that |⟨x⟩| = |x|.
example (hx : IsOfFinOrder x) : { x ^ n | n < orderOf x }.ncard = orderOf x
  := by --
  let N : Set ℕ := Finset.range (orderOf x)
  have heq : { x ^ n | n < orderOf x } = N.image (x ^ ·) := by
    dsimp only [N]
    rw [Finset.coe_range]
    rfl
  rw [heq]
  refine le_antisymm ?_ ?_
  · dsimp only [N]
    have : N.ncard = orderOf x := by
      rw [Set.ncard_coe_finset (Finset.range (orderOf x))]
      exact Finset.card_range (orderOf x)
    conv => rhs; rw [<-this]
    change ((x ^ ·) '' N).ncard ≤ N.ncard
    refine Set.ncard_image_le ?_
    exact Finset.finite_toSet (Finset.range (orderOf x))
  · refine Set.le_ncard_of_inj_on_range (x ^ ·) ?_ ?_ ?_
    · intro n hn
      refine ⟨n, ?_, rfl⟩
      dsimp only [N]
      rw [Finset.coe_range]
      exact hn
    · intro i hi j hj (heq : x ^ i = x ^ j)
      rw [IsOfFinOrder.pow_eq_pow_iff_modEq hx] at heq
      exact Nat.ModEq.eq_of_lt_of_lt heq hi hj
    · exact Set.toFinite ((x ^ ·) '' N) -- ∎

-- Different ways of writing ⟨x⟩ in Lean.
example : Subgroup.zpowers x = Subgroup.closure {x} := Subgroup.zpowers_eq_closure x

-- |⟨x⟩| = |x|. So if a group is generated by one element (or cyclic), then the
-- cardinality of that group is the order of that element.
--
-- Note that in Mathlib, the convention is that if a group element has infinite
-- order, then `orderOf` gives 0. Similarly if a type has infinite cardinality,
-- then `Nat.card` gives 0.
example (h : Subgroup.closure {x} = ⊤) : Nat.card H = orderOf x
  := by --
  refine (orderOf_eq_card_of_forall_mem_zpowers ?_).symm
  intro v
  rw [Subgroup.zpowers_eq_closure, h]
  exact Subgroup.mem_top v -- ∎

end Proposition2
